[general]
flip_aug = false
color_aug = false
keep_tokens_separator= "|||"
shuffle_caption = false
caption_tag_dropout_rate = 0
#caption_extension = ".txt"

#repeat this structure for each resolution bucket
[[datasets]]
# define the first resolution here
batch_size = 1
enable_bucket = true
resolution = [1024, 1024]

  [[datasets.subsets]]
  image_dir = "path_to_images"
  num_repeats = 1
  class_tokens = '[trigger] woman'